### ISSUE TITLE
System.NotImplementedException in RefactoringEssentials.CSharp.Diagnostics.RedundantUnsafeContextAnalyzer

### ISSUE THREAD

**Issue by arlm** [icsharpcode/RefactoringEssentials#259]
Code Analysis in VS 2015 Update 3 is breaking due to this error:

```
Warning AD0001: Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantUnsafeContextAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'The method or operation is not implemented.'.

Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantUnsafeContextAnalyzer' threw the following exception:

Exception occurred with following context:
Compilation: CLR.Extensions.Portable
SyntaxTree: C:\Users\amarcondes\Documents\GitHub\Extensions\src\CLR.Extensions.Portable\ReflectionExtensions.cs

System.NotImplementedException: The method or operation is not implemented.
   at RefactoringEssentials.SymbolExtensions.IsUnsafeVisitor.DefaultVisit(ISymbol node) in C:\projects\refactoringessentials\RefactoringEssentials\Util\SymbolExtensions.cs:line 691
   at Microsoft.CodeAnalysis.SymbolVisitor`1.VisitRangeVariable(IRangeVariableSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.Symbols.RangeVariableSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at RefactoringEssentials.SymbolExtensions.IsUnsafe(ISymbol member) in C:\projects\refactoringessentials\RefactoringEssentials\Util\SymbolExtensions.cs:line 678
   at RefactoringEssentials.CSharp.Diagnostics.RedundantUnsafeContextAnalyzer.GatherVisitor.VisitIdentifierName(IdentifierNameSyntax node) in C:\projects\refactoringessentials\RefactoringEssentials\CSharp\Diagnostics\Synced\RedundanciesInCode\RedundantUnsafeContextAnalyzer.cs:line 193
   at Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitBinaryExpression(BinaryExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BinaryExpressionSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitWhereClause(WhereClauseSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.WhereClauseSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitQueryBody(QueryBodySyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.QueryBodySyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitQueryExpression(QueryExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.QueryExpressionSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitEqualsValueClause(EqualsValueClauseSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.EqualsValueClauseSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitVariableDeclarator(VariableDeclaratorSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitVariableDeclaration(VariableDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at RefactoringEssentials.CSharp.Diagnostics.RedundantUnsafeContextAnalyzer.GatherVisitor.VisitClassDeclaration(ClassDeclarationSyntax node) in C:\projects\refactoringessentials\RefactoringEssentials\CSharp\Diagnostics\Synced\RedundanciesInCode\RedundantUnsafeContextAnalyzer.cs:line 123
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at RefactoringEssentials.CSharp.Diagnostics.RedundantUnsafeContextAnalyzer.<>c__DisplayClass3_0.<Initialize>b__1(SyntaxTreeAnalysisContext ctx) in C:\projects\refactoringessentials\RefactoringEssentials\CSharp\Diagnostics\Synced\RedundanciesInCode\RedundantUnsafeContextAnalyzer.cs:line 47
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass41_0.<ExecuteSyntaxTreeActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
```

**Comment by vip32** [comment]
confirmed, my vs2015 upd 3 is also throwing this during build

warning AD0001: Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantUnsafeContextAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'The method or operation is not implemented.'.

any way to disable this rule in the GlobalSuppressions.cs? this is not helping
```
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("RefactoringEssentials.CSharp.Diagnostics", "AD0001", Justification = "<Pending>")]
```

**Comment by Rpinski** [comment]
This would temporarily disable the analyzer:

```
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Code", "RECS0158:Unsafe modifier in redundant in unsafe context or when no unsafe constructs are used", Justification = "<Pending>", Scope = "member")]
```

**Comment by Rpinski** [comment]
Should be fixed now.

**Comment by vip32** [comment]
thanks for helping out. however adding that suppression to the file does not solve the problem for me. still see lots of AD0001 issues during build ;( What do you mean that it has been fixed by now? I use the current 4.4.0 version of the analyzer, is there a new version where this is fixed?

**Comment by Rpinski** [comment]
I meant this has been fixed in current development builds (master branch):
http://vsixgallery.com/extension/NR6Pack.Refactorings.Vsix..cd27e59b-5c56-4238-8931-c9bb745a7a7f/

**Comment by sm-g** [comment]
Does 4.4.0 version have fix for that?

**Comment by vmonatko** [comment]
Refactoring Essentials 5.2.0.0. Still got this error.
Warning	AD0001	Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantBaseQualifierAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Не удалось загрузить тип "Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer`9" из сборки "Microsoft.CodeAnalysis.Workspaces, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".'
